version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=usuario
      - DB_PASSWORD=password
      - DB_NAME=mibasededatos
      - DB_PORT=3306

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mibasededatos
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=password
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql